[project]
name = "llamacon-sf-2025-05-ghost-writers-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.77.0",
]
